---
- name: test default ssh port
  local_action: wait_for timeout={{ ssh_timeout }} port={{ ssh_port }} host={{ inventory_hostname }}
  sudo: false
  register: test_ssh
  ignore_errors: True
  tags: ssh

- debug: var=test_ssh

- name: set ansible_ssh_port to default
  set_fact: ansible_ssh_port=22
  when: test_ssh.elapsed == ssh_timeout
  tags: ssh

- name: ensure public key is in authorized_keys
  authorized_key: user={{ ansible_ssh_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: test_ssh.elapsed == ssh_timeout
  tags: ssh

- name: be sure ssh is configured
  template: src=etc/ssh/sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root
  when: test_ssh.elapsed == ssh_timeout
  tags: ssh

- name: restart ssh
  service: name=ssh state=restarted
  when: test_ssh.elapsed == ssh_timeout
  tags: ssh

- name: be sure ssh is running and enabled
  service: name=ssh state=running enabled=yes
  when: test_ssh.elapsed == ssh_timeout
  tags: ssh
